// This file was automatically generated by gyb
// DO NOT EDIT!
// Compiled from community_feedback.proto

#import "GEORPAmenityCorrections.h"
#import <ProtocolBuffer/PBConstants.h>
#import <ProtocolBuffer/PBHashUtil.h>
#import <ProtocolBuffer/PBDataReader.h>
#import <os/lock_private.h>

#if !__has_feature(objc_arc)
# error This generated file depends on ARC but it is not enabled
#endif

@implementation GEORPAmenityCorrections

- (instancetype)init
{
    self = [super init];
    if (self == nil) {
        return nil;
    }

    _readerLock = OS_UNFAIR_LOCK_INIT;
    return self;
}

- (instancetype)initWithData:(NSData *)data
{
    self = [super initWithData:data];
    if (self == nil) {
        return nil;
    }

    _readerLock = OS_UNFAIR_LOCK_INIT;
    return self;
}

- (void)dealloc
{
    PBRepeatedInt32Clear(&(self->_addedAmenities));
    PBRepeatedInt32Clear(&(self->_removedAmenities));
}

- (void)_readAddedAmenities {
    if (_flags.read_addedAmenities) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_addedAmenities) {
            static const uint32_t tags[] = {3, 0};
            GEORPAmenityCorrectionsReadSpecified(self, reader, tags);
        }
    }
}
- (NSUInteger)addedAmenitiesCount
{
    [self _readAddedAmenities];
    return _addedAmenities.count;
}
- (GEOPDAmenityType *)addedAmenities
{
    [self _readAddedAmenities];
    return _addedAmenities.list;
}
- (void)clearAddedAmenities
{
    _flags.read_addedAmenities = 1;
    _flags.wrote_addedAmenities = 1;
    PBRepeatedInt32Clear(&_addedAmenities);
}
- (void)addAddedAmenities:(GEOPDAmenityType)i
{
    [self _readAddedAmenities];
    [self _addNoFlagsAddedAmenities:i];
    _flags.read_addedAmenities = 1;
    _flags.wrote_addedAmenities = 1;
}
- (void)_addNoFlagsAddedAmenities:(GEOPDAmenityType)i
{
    PBRepeatedInt32Add(&_addedAmenities, i);
}
- (GEOPDAmenityType)addedAmenitiesAtIndex:(NSUInteger)idx
{
    [self _readAddedAmenities];
    if (_addedAmenities.count <= idx)
    {
        [[NSException exceptionWithName:NSRangeException reason:[NSString stringWithFormat:@"idx (%tu) is out of range (%tu)", idx, _addedAmenities.count] userInfo:nil] raise];
    }
    return _addedAmenities.list[idx];
}
- (void)setAddedAmenities:(GEOPDAmenityType *)list count:(NSUInteger)count
{
    _flags.read_addedAmenities = 1;
    _flags.wrote_addedAmenities = 1;
    PBRepeatedInt32Set(&_addedAmenities, list, count);
}
- (NSString *)addedAmenitiesAsString:(GEOPDAmenityType)value
{
    return GEOPDAmenityTypeAsString(value);
}
- (GEOPDAmenityType)StringAsAddedAmenities:(NSString *)str
{
    return StringAsGEOPDAmenityType(str);
}

- (void)_readRemovedAmenities {
    if (_flags.read_removedAmenities) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_removedAmenities) {
            static const uint32_t tags[] = {4, 0};
            GEORPAmenityCorrectionsReadSpecified(self, reader, tags);
        }
    }
}
- (NSUInteger)removedAmenitiesCount
{
    [self _readRemovedAmenities];
    return _removedAmenities.count;
}
- (GEOPDAmenityType *)removedAmenities
{
    [self _readRemovedAmenities];
    return _removedAmenities.list;
}
- (void)clearRemovedAmenities
{
    _flags.read_removedAmenities = 1;
    _flags.wrote_removedAmenities = 1;
    PBRepeatedInt32Clear(&_removedAmenities);
}
- (void)addRemovedAmenities:(GEOPDAmenityType)i
{
    [self _readRemovedAmenities];
    [self _addNoFlagsRemovedAmenities:i];
    _flags.read_removedAmenities = 1;
    _flags.wrote_removedAmenities = 1;
}
- (void)_addNoFlagsRemovedAmenities:(GEOPDAmenityType)i
{
    PBRepeatedInt32Add(&_removedAmenities, i);
}
- (GEOPDAmenityType)removedAmenitiesAtIndex:(NSUInteger)idx
{
    [self _readRemovedAmenities];
    if (_removedAmenities.count <= idx)
    {
        [[NSException exceptionWithName:NSRangeException reason:[NSString stringWithFormat:@"idx (%tu) is out of range (%tu)", idx, _removedAmenities.count] userInfo:nil] raise];
    }
    return _removedAmenities.list[idx];
}
- (void)setRemovedAmenities:(GEOPDAmenityType *)list count:(NSUInteger)count
{
    _flags.read_removedAmenities = 1;
    _flags.wrote_removedAmenities = 1;
    PBRepeatedInt32Set(&_removedAmenities, list, count);
}
- (NSString *)removedAmenitiesAsString:(GEOPDAmenityType)value
{
    return GEOPDAmenityTypeAsString(value);
}
- (GEOPDAmenityType)StringAsRemovedAmenities:(NSString *)str
{
    return StringAsGEOPDAmenityType(str);
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"%@ %@", [super description], [self dictionaryRepresentation]];
}

- (NSDictionary *)dictionaryRepresentation
{
    [self readAll:YES];
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    if (self->_addedAmenities.count > 0)
    {
        NSMutableArray *addedAmenitiesValues = [NSMutableArray arrayWithCapacity:self->_addedAmenities.count];
        for (NSUInteger i = 0; i < self->_addedAmenities.count; i++)
        {
            [addedAmenitiesValues addObject:GEOPDAmenityTypeAsString(self->_addedAmenities.list[i])];
        }
        [dict setObject:addedAmenitiesValues forKey:@"added_amenities"];
    }

    if (self->_removedAmenities.count > 0)
    {
        NSMutableArray *removedAmenitiesValues = [NSMutableArray arrayWithCapacity:self->_removedAmenities.count];
        for (NSUInteger i = 0; i < self->_removedAmenities.count; i++)
        {
            [removedAmenitiesValues addObject:GEOPDAmenityTypeAsString(self->_removedAmenities.list[i])];
        }
        [dict setObject:removedAmenitiesValues forKey:@"removed_amenities"];
    }


    if (_unknownFields)
        [dict setObject:[_unknownFields dictionaryRepresentation] forKey:@"Unknown Fields"];

    return dict;
}


#define TAG_PARSE_ALL_RECURSIVE     (UINT32_MAX)
#define TAG_PARSE_ALL_NON_RECURSIVE (UINT32_MAX-1)
#define TAG_PARSE_INITIAL           (UINT32_MAX-2)
#define TAG_UNKNOWN_FIELDS          (UINT32_MAX-3)

- (void)readAll:(BOOL)recursively {
    os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (reader == nil) return;
    @synchronized(reader) {
        static const uint32_t recursiveTag[] = {TAG_PARSE_ALL_RECURSIVE, 0};
        static const uint32_t nonRecursiveTag[] = {TAG_PARSE_ALL_NON_RECURSIVE, 0};
        GEORPAmenityCorrectionsReadSpecified(self, reader, recursively ? recursiveTag : nonRecursiveTag);
    }
}
BOOL GEORPAmenityCorrectionsReadAllFrom(__unsafe_unretained GEORPAmenityCorrections *self, __unsafe_unretained PBDataReader *reader, BOOL recursively) {
    if (self->_readerMarkLength != 0) {
        [NSException raise:NSInvalidArgumentException format:@"GEORPAmenityCorrectionsReadAllFrom can only be called once per object"];
        return NO;
    }

    if (reader.position > UINT32_MAX || reader.length > UINT32_MAX) {
        os_log_fault(OS_LOG_DEFAULT, "Cannot decode data with position/length > UINT32_MAX");
        return NO;
    }

    static const uint32_t recursiveTag[] = {TAG_PARSE_INITIAL, TAG_PARSE_ALL_RECURSIVE, 0};
    static const uint32_t initialTag[] = {TAG_PARSE_INITIAL, 0};

    @synchronized(reader) {
        os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
        self->_reader = reader;
        os_unfair_lock_unlock(&(self->_readerLock));

        self->_readerMarkPos = (uint32_t)reader.position;
        self->_readerMarkLength = (uint32_t)reader.length;
        BOOL result = GEORPAmenityCorrectionsReadSpecified(self, reader, recursively ? recursiveTag : initialTag);
        return result;
    }
}

BOOL GEORPAmenityCorrectionsReadFrom(__unsafe_unretained GEORPAmenityCorrections *self, __unsafe_unretained PBDataReader *reader) {
    @synchronized(reader) {
        return GEORPAmenityCorrectionsReadAllFrom(self, reader, NO);
    }
}

BOOL GEORPAmenityCorrectionsReadSpecified(__unsafe_unretained GEORPAmenityCorrections *self, __unsafe_unretained PBDataReader *reader, const uint32_t *tags) {
    if (reader == nil) {
        return NO;
    }
    reader->_length = (NSUInteger)self->_readerMarkLength;
    [reader seekToOffset:(NSUInteger)self->_readerMarkPos];
    uint32_t readLazyCount = 0
        + self->_flags.read_addedAmenities
        + self->_flags.read_removedAmenities
        + self->_flags.read_unknownFields
        ;
    #define requiredLazyFieldCount 1 // objc_msg_parse_all_threshold = 0.8

    BOOL readAll = NO;
    __attribute__((unused)) BOOL recursively = NO;
    BOOL shouldParseUnknown = NO;
    BOOL isInitial = NO;
    size_t tagsRemaining = 0;
    for (; tags[tagsRemaining] != 0; ++tagsRemaining) {
        switch (tags[tagsRemaining]) {
            case TAG_PARSE_ALL_RECURSIVE:
                recursively = YES;
                readAll = YES;
                shouldParseUnknown = YES;
                break;
            case TAG_PARSE_ALL_NON_RECURSIVE:
                readAll = YES;
                shouldParseUnknown = YES;
                break;
            case TAG_PARSE_INITIAL:
                isInitial = YES;
                break;
            case TAG_UNKNOWN_FIELDS:
                shouldParseUnknown = YES;
                ++readLazyCount;
                break;
            default:
                ++readLazyCount;
                break;
            }
    }
    if (!readAll && readLazyCount >= requiredLazyFieldCount) {
        readAll = YES;
        shouldParseUnknown = YES;
    }
    const BOOL stopWhenNoMoreTagsRemaining = !(readAll || shouldParseUnknown);
    if (readAll || isInitial) tags = NULL;

    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }
        
        BOOL shouldParseTag = readAll;
        for (size_t i = 0; tags != NULL && !shouldParseTag && tags[i] != 0; ++i) {
            shouldParseTag = (tags[i] == tag);
        }

        switch (tag) {

            case 3 /* addedAmenities */:
            {
                if (!shouldParseTag || self->_flags.read_addedAmenities) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    break;
                }
            if (TYPE_LENGTH_DELIMITED == aType)
                {
                    PBDataReaderMark mark_addedAmenities;
                    BOOL markError = !PBReaderPlaceMark(reader, &mark_addedAmenities);
                    if (markError)
                    {
                        return NO;
                    }
                    while (PBReaderHasMoreData(reader))
                    {
                        GEOPDAmenityType new_addedAmenities = PBReaderReadInt32(reader);
                        PBRepeatedInt32Add(&(self->_addedAmenities), new_addedAmenities);
                    }
                    PBReaderRecallMark(reader, &mark_addedAmenities);
                }
                else
                {
                    PBRepeatedInt32Add(&(self->_addedAmenities), PBReaderReadInt32(reader));
                }

            }
            break;
            case 4 /* removedAmenities */:
            {
                if (!shouldParseTag || self->_flags.read_removedAmenities) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    break;
                }
            if (TYPE_LENGTH_DELIMITED == aType)
                {
                    PBDataReaderMark mark_removedAmenities;
                    BOOL markError = !PBReaderPlaceMark(reader, &mark_removedAmenities);
                    if (markError)
                    {
                        return NO;
                    }
                    while (PBReaderHasMoreData(reader))
                    {
                        GEOPDAmenityType new_removedAmenities = PBReaderReadInt32(reader);
                        PBRepeatedInt32Add(&(self->_removedAmenities), new_removedAmenities);
                    }
                    PBReaderRecallMark(reader, &mark_removedAmenities);
                }
                else
                {
                    PBRepeatedInt32Add(&(self->_removedAmenities), PBReaderReadInt32(reader));
                }

            }
            break;
            default:
                if (!shouldParseUnknown || self->_flags.read_unknownFields) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    break;
                }
                if (!self->_unknownFields)
                    self->_unknownFields = [[PBUnknownFields alloc] init];
                if (!PBUnknownFieldAdd(self->_unknownFields, tag, aType, reader))
                    return NO;
                break;
        }
        if (stopWhenNoMoreTagsRemaining && tagsRemaining == 0) {
            break;
        }
    }

    if (shouldParseUnknown) {
        self->_flags.read_unknownFields = YES;
    }

    if (readAll) {
        if (recursively) {
        }
        self->_flags.read_addedAmenities = YES;
        self->_flags.read_removedAmenities = YES;
    } else {
        for (size_t i = 0; tags != NULL && tags[i] != 0; ++i) {
            switch (tags[i]) {
                case 3 /* addedAmenities */:
                    self->_flags.read_addedAmenities = YES;
                    break;
                case 4 /* removedAmenities */:
                    self->_flags.read_removedAmenities = YES;
                    break;
            }
        }
    }

    #undef requiredLazyFieldCount
    if (readAll) {
        // reader is __unsafe_unretained
        const BOOL hadError = PBReaderHasError(reader);
        os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
        self->_reader = nil;
        os_unfair_lock_unlock(&(self->_readerLock));
        return !hadError;
    }
    return !PBReaderHasError(reader);
}

+ (BOOL)isValid:(__unsafe_unretained PBDataReader *)reader
{
    return GEORPAmenityCorrectionsIsValid(reader);
}

BOOL GEORPAmenityCorrectionsIsValid(__unsafe_unretained PBDataReader *reader) {
    PBDataReaderMark resetMark;
    resetMark.pos = reader.position;
    resetMark.length = reader.length;
    #define returnValue(X) do { \
        const BOOL v = X; \
        PBReaderRecallMark(reader, &resetMark); \
        return v; \
    } while(0)
    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }

        switch (tag) {

            case 3 /* addedAmenities */:
                if (TYPE_LENGTH_DELIMITED == aType)
                {
                    PBDataReaderMark mark_addedAmenities;
                    if (!PBReaderPlaceMark(reader, &mark_addedAmenities))
                        returnValue(NO);
                    while (PBReaderHasMoreData(reader))
                        PBReaderReadInt32(reader);
                    PBReaderRecallMark(reader, &mark_addedAmenities);
                }
                else if (TYPE_VARINT != aType)
                    returnValue(NO);
                else
                    PBReaderReadInt32(reader);
                break;
            case 4 /* removedAmenities */:
                if (TYPE_LENGTH_DELIMITED == aType)
                {
                    PBDataReaderMark mark_removedAmenities;
                    if (!PBReaderPlaceMark(reader, &mark_removedAmenities))
                        returnValue(NO);
                    while (PBReaderHasMoreData(reader))
                        PBReaderReadInt32(reader);
                    PBReaderRecallMark(reader, &mark_removedAmenities);
                }
                else if (TYPE_VARINT != aType)
                    returnValue(NO);
                else
                    PBReaderReadInt32(reader);
                break;
            default:
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    returnValue(NO);
                break;
        }
    }
    returnValue(!PBReaderHasError(reader));
    #undef returnValue
}

- (BOOL)readFrom:(PBDataReader *)reader
{
    return GEORPAmenityCorrectionsReadAllFrom(self, reader, NO);
}

- (void)writeTo:(PBDataWriter *)writer
{
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    @synchronized(reader) {
        if (reader) {
            if (!GEORPAmenityCorrectionsIsDirty(self)) {
                reader->_length = (NSUInteger)_readerMarkLength;
                [reader seekToOffset:(NSUInteger)_readerMarkPos];
                uint32_t length = (_readerMarkLength - _readerMarkPos);
                NSData *data = [reader readBytes:length];
                [writer writeData:data];
                return;
            }
        }
    }

    [self readAll:NO];

    /* addedAmenities */
    {
        if (self->_addedAmenities.count)
        {
            NSUInteger i_addedAmenities;
            for (i_addedAmenities = 0; i_addedAmenities < self->_addedAmenities.count; i_addedAmenities++)
            {
                PBDataWriterWriteInt32Field(writer, self->_addedAmenities.list[i_addedAmenities], 3);
            }
        }

    }

    /* removedAmenities */
    {
        if (self->_removedAmenities.count)
        {
            NSUInteger i_removedAmenities;
            for (i_removedAmenities = 0; i_removedAmenities < self->_removedAmenities.count; i_removedAmenities++)
            {
                PBDataWriterWriteInt32Field(writer, self->_removedAmenities.list[i_removedAmenities], 4);
            }
        }

    }
    /* Unknown Fields */
    {
        [_unknownFields writeTo:writer];
    }
}

BOOL GEORPAmenityCorrectionsIsDirty(__unsafe_unretained GEORPAmenityCorrections *self)
{
    if (self == nil) {
        return NO;
    }
    
    BOOL dirty = NO
        || self->_flags.wrote_addedAmenities
        || self->_flags.read_addedAmenities
        || self->_flags.wrote_removedAmenities
        || self->_flags.read_removedAmenities
        || self->_flags.wrote_unknownFields
    ;


    return dirty;
}


- (void)copyTo:(GEORPAmenityCorrections *)other
{
    [self readAll:NO];
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    other->_reader = _reader;
    other->_readerMarkPos = _readerMarkPos;
    other->_readerMarkLength = _readerMarkLength;
    os_unfair_lock_unlock(&_readerLock);
    if ([self addedAmenitiesCount])
    {
        [other clearAddedAmenities];
        NSUInteger addedAmenitiesCnt = [self addedAmenitiesCount];
        for (NSUInteger i = 0; i < addedAmenitiesCnt; i++)
        {
            [other addAddedAmenities:[self addedAmenitiesAtIndex:i]];
        }
    }
    if ([self removedAmenitiesCount])
    {
        [other clearRemovedAmenities];
        NSUInteger removedAmenitiesCnt = [self removedAmenitiesCount];
        for (NSUInteger i = 0; i < removedAmenitiesCnt; i++)
        {
            [other addRemovedAmenities:[self removedAmenitiesAtIndex:i]];
        }
    }
}

- (id)copyWithZone:(NSZone *)zone
{
    GEORPAmenityCorrections *copy = [[[self class] allocWithZone:zone] init];
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    @synchronized(reader) {
        if (reader) {
            BOOL wroteAny = NO
                || _flags.wrote_addedAmenities
                || _flags.wrote_removedAmenities
                || _flags.wrote_unknownFields
            ;
            if (!wroteAny) {
                reader->_length = (NSUInteger)_readerMarkLength;
                [reader seekToOffset:(NSUInteger)_readerMarkPos];
                GEORPAmenityCorrectionsReadAllFrom(copy, reader, NO);
                return copy;
            }
            [self readAll:NO];
        }
    }
    PBRepeatedInt32Copy(&(copy->_addedAmenities), &_addedAmenities);
    PBRepeatedInt32Copy(&(copy->_removedAmenities), &_removedAmenities);
    copy->_unknownFields = _unknownFields;
    return copy;
}


- (BOOL)isEqual:(id)object
{
    GEORPAmenityCorrections *other = (GEORPAmenityCorrections *)object;
    if (![other isMemberOfClass:[self class]]) {
        return NO;
    }
    [self readAll:YES];
    [other readAll:YES];


    return YES
    &&
    PBRepeatedInt32IsEqual(&(self->_addedAmenities), &(other->_addedAmenities))

    &&
    PBRepeatedInt32IsEqual(&(self->_removedAmenities), &(other->_removedAmenities))

    ;
}

- (NSUInteger)hash
{
    [self readAll:YES];
    NSUInteger value = 0;

    return value
    ^
    PBRepeatedInt32Hash(&(self->_addedAmenities))
    ^
    PBRepeatedInt32Hash(&(self->_removedAmenities))
    ;
}

- (void)mergeFrom:(GEORPAmenityCorrections *)other
{
    [other readAll:NO];
    NSUInteger addedAmenitiesCnt = [other addedAmenitiesCount];
    for (NSUInteger i = 0; i < addedAmenitiesCnt; i++)
    {
        [self addAddedAmenities:[other addedAmenitiesAtIndex:i]];
    }
    NSUInteger removedAmenitiesCnt = [other removedAmenitiesCount];
    for (NSUInteger i = 0; i < removedAmenitiesCnt; i++)
    {
        [self addRemovedAmenities:[other removedAmenitiesAtIndex:i]];
    }
}

- (PBUnknownFields *)unknownFields
{
    if (_flags.read_unknownFields) return _unknownFields;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return _unknownFields;
    @synchronized(reader) {
        if (!_flags.read_unknownFields) {
            static const uint32_t tags[] = {TAG_UNKNOWN_FIELDS, 0};
            GEORPAmenityCorrectionsReadSpecified(self, reader, tags);
        }
    }
    return _unknownFields;
}
- (void)clearUnknownFields:(BOOL)recursively
{
    _flags.read_unknownFields = 1;
    _flags.wrote_unknownFields = 1;
    _unknownFields = nil;
    if (!recursively) {
        return;
    }
    [self readAll:NO];
}

@end


