// This file was automatically generated by gyb
// DO NOT EDIT!
// Compiled from reportaproblem.proto

#import "GEORPCorrectedSearch.h"
#import <ProtocolBuffer/PBConstants.h>
#import <ProtocolBuffer/PBHashUtil.h>
#import <ProtocolBuffer/PBDataReader.h>
#import <os/lock_private.h>

#import <GeoServices/GEOPDPlaceRequest.h>
#import <GeoServices/GEOPDPlaceResponse.h>
#import <GeoServices/GEOPlaceSearchRequest.h>
#import <GeoServices/GEOPlaceSearchResponse.h>

#if !__has_feature(objc_arc)
# error This generated file depends on ARC but it is not enabled
#endif

@implementation GEORPCorrectedSearch

- (instancetype)init
{
    self = [super init];
    if (self == nil) {
        return nil;
    }

    _readerLock = OS_UNFAIR_LOCK_INIT;
    return self;
}

- (instancetype)initWithData:(NSData *)data
{
    self = [super initWithData:data];
    if (self == nil) {
        return nil;
    }

    _readerLock = OS_UNFAIR_LOCK_INIT;
    return self;
}

- (void)_readPlaceSearchRequest {
    if (_flags.read_placeSearchRequest) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_placeSearchRequest) {
            static const uint32_t tags[] = {1, 0};
            GEORPCorrectedSearchReadSpecified(self, reader, tags);
        }
    }
}
- (BOOL)hasPlaceSearchRequest
{
    [self _readPlaceSearchRequest];
    return _placeSearchRequest != nil;
}
- (GEOPlaceSearchRequest *)placeSearchRequest
{
    [self _readPlaceSearchRequest];
    return _placeSearchRequest;
}
- (void)setPlaceSearchRequest:(GEOPlaceSearchRequest *)v
{
    _flags.read_placeSearchRequest = 1;
    _flags.wrote_placeSearchRequest = 1;
    _placeSearchRequest = v;
}

- (void)_readPlaceSearchResponse {
    if (_flags.read_placeSearchResponse) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_placeSearchResponse) {
            static const uint32_t tags[] = {2, 0};
            GEORPCorrectedSearchReadSpecified(self, reader, tags);
        }
    }
}
- (BOOL)hasPlaceSearchResponse
{
    [self _readPlaceSearchResponse];
    return _placeSearchResponse != nil;
}
- (GEOPlaceSearchResponse *)placeSearchResponse
{
    [self _readPlaceSearchResponse];
    return _placeSearchResponse;
}
- (void)setPlaceSearchResponse:(GEOPlaceSearchResponse *)v
{
    _flags.read_placeSearchResponse = 1;
    _flags.wrote_placeSearchResponse = 1;
    _placeSearchResponse = v;
}

- (uint32_t)originalSearchResultIndex
{
    return _originalSearchResultIndex;
}
- (void)setOriginalSearchResultIndex:(uint32_t)v
{
    _flags.wrote_originalSearchResultIndex = 1;
    _flags.has_originalSearchResultIndex = 1;
    _originalSearchResultIndex = v;
}
- (void)setHasOriginalSearchResultIndex:(BOOL)f
{
    _flags.wrote_originalSearchResultIndex = 1;
    _flags.has_originalSearchResultIndex = f ? 1 : 0;
}
- (BOOL)hasOriginalSearchResultIndex
{
    return (BOOL)_flags.has_originalSearchResultIndex;
}

- (uint32_t)correctedSearchResultIndex
{
    return _correctedSearchResultIndex;
}
- (void)setCorrectedSearchResultIndex:(uint32_t)v
{
    _flags.wrote_correctedSearchResultIndex = 1;
    _flags.has_correctedSearchResultIndex = 1;
    _correctedSearchResultIndex = v;
}
- (void)setHasCorrectedSearchResultIndex:(BOOL)f
{
    _flags.wrote_correctedSearchResultIndex = 1;
    _flags.has_correctedSearchResultIndex = f ? 1 : 0;
}
- (BOOL)hasCorrectedSearchResultIndex
{
    return (BOOL)_flags.has_correctedSearchResultIndex;
}

- (void)_readPreferredSearchDisplayLocation {
    if (_flags.read_preferredSearchDisplayLocation) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_preferredSearchDisplayLocation) {
            static const uint32_t tags[] = {5, 0};
            GEORPCorrectedSearchReadSpecified(self, reader, tags);
        }
    }
}
- (BOOL)hasPreferredSearchDisplayLocation
{
    [self _readPreferredSearchDisplayLocation];
    return _preferredSearchDisplayLocation != nil;
}
- (NSString *)preferredSearchDisplayLocation
{
    [self _readPreferredSearchDisplayLocation];
    return _preferredSearchDisplayLocation;
}
- (void)setPreferredSearchDisplayLocation:(NSString *)v
{
    _flags.read_preferredSearchDisplayLocation = 1;
    _flags.wrote_preferredSearchDisplayLocation = 1;
    _preferredSearchDisplayLocation = v;
}

- (void)_readPlaceRequest {
    if (_flags.read_placeRequest) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_placeRequest) {
            static const uint32_t tags[] = {6, 0};
            GEORPCorrectedSearchReadSpecified(self, reader, tags);
        }
    }
}
- (BOOL)hasPlaceRequest
{
    [self _readPlaceRequest];
    return _placeRequest != nil;
}
- (GEOPDPlaceRequest *)placeRequest
{
    [self _readPlaceRequest];
    return _placeRequest;
}
- (void)setPlaceRequest:(GEOPDPlaceRequest *)v
{
    _flags.read_placeRequest = 1;
    _flags.wrote_placeRequest = 1;
    _placeRequest = v;
}

- (void)_readPlaceResponse {
    if (_flags.read_placeResponse) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_placeResponse) {
            static const uint32_t tags[] = {7, 0};
            GEORPCorrectedSearchReadSpecified(self, reader, tags);
        }
    }
}
- (BOOL)hasPlaceResponse
{
    [self _readPlaceResponse];
    return _placeResponse != nil;
}
- (GEOPDPlaceResponse *)placeResponse
{
    [self _readPlaceResponse];
    return _placeResponse;
}
- (void)setPlaceResponse:(GEOPDPlaceResponse *)v
{
    _flags.read_placeResponse = 1;
    _flags.wrote_placeResponse = 1;
    _placeResponse = v;
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"%@ %@", [super description], [self dictionaryRepresentation]];
}

- (NSDictionary *)dictionaryRepresentation
{
    [self readAll:YES];
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    {
        GEOPlaceSearchRequest * value = self.placeSearchRequest;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"place_search_request"];
        }
    }

    {
        GEOPlaceSearchResponse * value = self.placeSearchResponse;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"place_search_response"];
        }
    }

    if (self->_flags.has_originalSearchResultIndex)
    {
        [dict setObject:@(self->_originalSearchResultIndex) forKey:@"original_search_result_index"];
    }

    if (self->_flags.has_correctedSearchResultIndex)
    {
        [dict setObject:@(self->_correctedSearchResultIndex) forKey:@"corrected_search_result_index"];
    }

    {
        NSString * value = self.preferredSearchDisplayLocation;
        if (value) {
            [dict setObject:value forKey:@"preferred_search_display_location"];
        }
    }

    {
        GEOPDPlaceRequest * value = self.placeRequest;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"place_request"];
        }
    }

    {
        GEOPDPlaceResponse * value = self.placeResponse;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"place_response"];
        }
    }



    return dict;
}


#define TAG_PARSE_ALL_RECURSIVE     (UINT32_MAX)
#define TAG_PARSE_ALL_NON_RECURSIVE (UINT32_MAX-1)
#define TAG_PARSE_INITIAL           (UINT32_MAX-2)
#define TAG_UNKNOWN_FIELDS          (UINT32_MAX-3)

- (void)readAll:(BOOL)recursively {
    os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (reader == nil) return;
    @synchronized(reader) {
        static const uint32_t recursiveTag[] = {TAG_PARSE_ALL_RECURSIVE, 0};
        static const uint32_t nonRecursiveTag[] = {TAG_PARSE_ALL_NON_RECURSIVE, 0};
        GEORPCorrectedSearchReadSpecified(self, reader, recursively ? recursiveTag : nonRecursiveTag);
    }
}
BOOL GEORPCorrectedSearchReadAllFrom(__unsafe_unretained GEORPCorrectedSearch *self, __unsafe_unretained PBDataReader *reader, BOOL recursively) {
    if (self->_readerMarkLength != 0) {
        [NSException raise:NSInvalidArgumentException format:@"GEORPCorrectedSearchReadAllFrom can only be called once per object"];
        return NO;
    }

    if (reader.position > UINT32_MAX || reader.length > UINT32_MAX) {
        os_log_fault(OS_LOG_DEFAULT, "Cannot decode data with position/length > UINT32_MAX");
        return NO;
    }

    static const uint32_t recursiveTag[] = {TAG_PARSE_INITIAL, TAG_PARSE_ALL_RECURSIVE, 0};
    static const uint32_t initialTag[] = {TAG_PARSE_INITIAL, 0};

    @synchronized(reader) {
        os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
        self->_reader = reader;
        os_unfair_lock_unlock(&(self->_readerLock));

        self->_readerMarkPos = (uint32_t)reader.position;
        self->_readerMarkLength = (uint32_t)reader.length;
        BOOL result = GEORPCorrectedSearchReadSpecified(self, reader, recursively ? recursiveTag : initialTag);
        return result;
    }
}

BOOL GEORPCorrectedSearchReadFrom(__unsafe_unretained GEORPCorrectedSearch *self, __unsafe_unretained PBDataReader *reader) {
    @synchronized(reader) {
        return GEORPCorrectedSearchReadAllFrom(self, reader, NO);
    }
}

BOOL GEORPCorrectedSearchReadSpecified(__unsafe_unretained GEORPCorrectedSearch *self, __unsafe_unretained PBDataReader *reader, const uint32_t *tags) {
    if (reader == nil) {
        return NO;
    }
    reader->_length = (NSUInteger)self->_readerMarkLength;
    [reader seekToOffset:(NSUInteger)self->_readerMarkPos];
    uint32_t readLazyCount = 0
        + self->_flags.read_placeSearchRequest
        + self->_flags.read_placeSearchResponse
        + self->_flags.read_preferredSearchDisplayLocation
        + self->_flags.read_placeRequest
        + self->_flags.read_placeResponse
        ;
    #define requiredLazyFieldCount 4 // objc_msg_parse_all_threshold = 0.8

    BOOL readAll = NO;
    __attribute__((unused)) BOOL recursively = NO;
    BOOL isInitial = NO;
    size_t tagsRemaining = 0;
    for (; tags[tagsRemaining] != 0; ++tagsRemaining) {
        switch (tags[tagsRemaining]) {
            case TAG_PARSE_ALL_RECURSIVE:
                recursively = YES;
                readAll = YES;
                break;
            case TAG_PARSE_ALL_NON_RECURSIVE:
                readAll = YES;
                break;
            case TAG_PARSE_INITIAL:
                isInitial = YES;
                break;
            default:
                ++readLazyCount;
                break;
            }
    }
    if (!readAll && readLazyCount >= requiredLazyFieldCount) {
        readAll = YES;
    }
    const BOOL stopWhenNoMoreTagsRemaining = !readAll;
    if (readAll || isInitial) tags = NULL;

    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }
        
        BOOL shouldParseTag = readAll;
        for (size_t i = 0; tags != NULL && !shouldParseTag && tags[i] != 0; ++i) {
            shouldParseTag = (tags[i] == tag);
        }

        switch (tag) {

            case 1 /* placeSearchRequest */:
            {
                if (!shouldParseTag || self->_flags.read_placeSearchRequest) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    if (shouldParseTag && self->_flags.read_placeSearchRequest) {
                        --tagsRemaining;
                    }
                    break;
                }
                GEOPlaceSearchRequest *new_placeSearchRequest = [[GEOPlaceSearchRequest alloc] init];
                self->_placeSearchRequest = new_placeSearchRequest;
                PBDataReaderMark mark_placeSearchRequest;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_placeSearchRequest);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEOPlaceSearchRequestReadAllFrom(new_placeSearchRequest, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_placeSearchRequest);

                --tagsRemaining;
            }
            break;
            case 2 /* placeSearchResponse */:
            {
                if (!shouldParseTag || self->_flags.read_placeSearchResponse) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    if (shouldParseTag && self->_flags.read_placeSearchResponse) {
                        --tagsRemaining;
                    }
                    break;
                }
                GEOPlaceSearchResponse *new_placeSearchResponse = [[GEOPlaceSearchResponse alloc] init];
                self->_placeSearchResponse = new_placeSearchResponse;
                PBDataReaderMark mark_placeSearchResponse;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_placeSearchResponse);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEOPlaceSearchResponseReadAllFrom(new_placeSearchResponse, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_placeSearchResponse);

                --tagsRemaining;
            }
            break;
            case 3 /* originalSearchResultIndex */:
            {
                if (!isInitial) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    break;
                }
                self->_flags.has_originalSearchResultIndex = YES;
                self->_originalSearchResultIndex = PBReaderReadUint32(reader);

            }
            break;
            case 4 /* correctedSearchResultIndex */:
            {
                if (!isInitial) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    break;
                }
                self->_flags.has_correctedSearchResultIndex = YES;
                self->_correctedSearchResultIndex = PBReaderReadUint32(reader);

            }
            break;
            case 5 /* preferredSearchDisplayLocation */:
            {
                if (!shouldParseTag || self->_flags.read_preferredSearchDisplayLocation) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    if (shouldParseTag && self->_flags.read_preferredSearchDisplayLocation) {
                        --tagsRemaining;
                    }
                    break;
                }
                NSString * new_preferredSearchDisplayLocation = PBReaderReadString(reader);
                self->_preferredSearchDisplayLocation = new_preferredSearchDisplayLocation;

                --tagsRemaining;
            }
            break;
            case 6 /* placeRequest */:
            {
                if (!shouldParseTag || self->_flags.read_placeRequest) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    if (shouldParseTag && self->_flags.read_placeRequest) {
                        --tagsRemaining;
                    }
                    break;
                }
                GEOPDPlaceRequest *new_placeRequest = [[GEOPDPlaceRequest alloc] init];
                self->_placeRequest = new_placeRequest;
                PBDataReaderMark mark_placeRequest;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_placeRequest);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEOPDPlaceRequestReadAllFrom(new_placeRequest, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_placeRequest);

                --tagsRemaining;
            }
            break;
            case 7 /* placeResponse */:
            {
                if (!shouldParseTag || self->_flags.read_placeResponse) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    if (shouldParseTag && self->_flags.read_placeResponse) {
                        --tagsRemaining;
                    }
                    break;
                }
                GEOPDPlaceResponse *new_placeResponse = [[GEOPDPlaceResponse alloc] init];
                self->_placeResponse = new_placeResponse;
                PBDataReaderMark mark_placeResponse;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_placeResponse);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEOPDPlaceResponseReadAllFrom(new_placeResponse, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_placeResponse);

                --tagsRemaining;
            }
            break;
            default:
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    return NO;
                break;
        }
        if (stopWhenNoMoreTagsRemaining && tagsRemaining == 0) {
            break;
        }
    }


    if (readAll) {
        if (recursively) {
            [self->_placeSearchRequest readAll:YES];
            [self->_placeSearchResponse readAll:YES];
            [self->_placeRequest readAll:YES];
            [self->_placeResponse readAll:YES];
        }
        self->_flags.read_placeSearchRequest = YES;
        self->_flags.read_placeSearchResponse = YES;
        self->_flags.read_preferredSearchDisplayLocation = YES;
        self->_flags.read_placeRequest = YES;
        self->_flags.read_placeResponse = YES;
    } else {
        for (size_t i = 0; tags != NULL && tags[i] != 0; ++i) {
            switch (tags[i]) {
                case 1 /* placeSearchRequest */:
                    self->_flags.read_placeSearchRequest = YES;
                    break;
                case 2 /* placeSearchResponse */:
                    self->_flags.read_placeSearchResponse = YES;
                    break;
                case 5 /* preferredSearchDisplayLocation */:
                    self->_flags.read_preferredSearchDisplayLocation = YES;
                    break;
                case 6 /* placeRequest */:
                    self->_flags.read_placeRequest = YES;
                    break;
                case 7 /* placeResponse */:
                    self->_flags.read_placeResponse = YES;
                    break;
            }
        }
    }

    #undef requiredLazyFieldCount
    if (readAll) {
        // reader is __unsafe_unretained
        const BOOL hadError = PBReaderHasError(reader);
        os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
        self->_reader = nil;
        os_unfair_lock_unlock(&(self->_readerLock));
        return !hadError;
    }
    return !PBReaderHasError(reader);
}

+ (BOOL)isValid:(__unsafe_unretained PBDataReader *)reader
{
    return GEORPCorrectedSearchIsValid(reader);
}

BOOL GEORPCorrectedSearchIsValid(__unsafe_unretained PBDataReader *reader) {
    PBDataReaderMark resetMark;
    resetMark.pos = reader.position;
    resetMark.length = reader.length;
    #define returnValue(X) do { \
        const BOOL v = X; \
        PBReaderRecallMark(reader, &resetMark); \
        return v; \
    } while(0)
    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }

        switch (tag) {

            case 1 /* placeSearchRequest */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_placeSearchRequest;
                    if (!PBReaderPlaceMark(reader, &mark_placeSearchRequest))
                        returnValue(NO);
                    if (!GEOPlaceSearchRequestIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_placeSearchRequest);
                }
                break;
            case 2 /* placeSearchResponse */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_placeSearchResponse;
                    if (!PBReaderPlaceMark(reader, &mark_placeSearchResponse))
                        returnValue(NO);
                    if (!GEOPlaceSearchResponseIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_placeSearchResponse);
                }
                break;
            case 3 /* originalSearchResultIndex */:
                if (TYPE_VARINT != aType)
                    returnValue(NO);
                PBReaderReadUint32(reader);
                break;
            case 4 /* correctedSearchResultIndex */:
                if (TYPE_VARINT != aType)
                    returnValue(NO);
                PBReaderReadUint32(reader);
                break;
            case 5 /* preferredSearchDisplayLocation */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    returnValue(NO);
                break;
                break;
            case 6 /* placeRequest */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_placeRequest;
                    if (!PBReaderPlaceMark(reader, &mark_placeRequest))
                        returnValue(NO);
                    if (!GEOPDPlaceRequestIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_placeRequest);
                }
                break;
            case 7 /* placeResponse */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_placeResponse;
                    if (!PBReaderPlaceMark(reader, &mark_placeResponse))
                        returnValue(NO);
                    if (!GEOPDPlaceResponseIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_placeResponse);
                }
                break;
            default:
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    returnValue(NO);
                break;
        }
    }
    returnValue(!PBReaderHasError(reader));
    #undef returnValue
}

- (BOOL)readFrom:(PBDataReader *)reader
{
    return GEORPCorrectedSearchReadAllFrom(self, reader, NO);
}

- (void)writeTo:(PBDataWriter *)writer
{
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    @synchronized(reader) {
        if (reader) {
            if (!GEORPCorrectedSearchIsDirty(self)) {
                reader->_length = (NSUInteger)_readerMarkLength;
                [reader seekToOffset:(NSUInteger)_readerMarkPos];
                uint32_t length = (_readerMarkLength - _readerMarkPos);
                NSData *data = [reader readBytes:length];
                [writer writeData:data];
                return;
            }
        }
    }

    [self readAll:NO];

    /* placeSearchRequest */
    {
        if (self->_placeSearchRequest != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_placeSearchRequest, 1);
        }
    }

    /* placeSearchResponse */
    {
        if (self->_placeSearchResponse != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_placeSearchResponse, 2);
        }
    }

    /* originalSearchResultIndex */
    {
        if (self->_flags.has_originalSearchResultIndex)
        {
            PBDataWriterWriteUint32Field(writer, self->_originalSearchResultIndex, 3);
        }
    }

    /* correctedSearchResultIndex */
    {
        if (self->_flags.has_correctedSearchResultIndex)
        {
            PBDataWriterWriteUint32Field(writer, self->_correctedSearchResultIndex, 4);
        }
    }

    /* preferredSearchDisplayLocation */
    {
        if (self->_preferredSearchDisplayLocation)
        {
            PBDataWriterWriteStringField(writer, self->_preferredSearchDisplayLocation, 5);
        }
    }

    /* placeRequest */
    {
        if (self->_placeRequest != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_placeRequest, 6);
        }
    }

    /* placeResponse */
    {
        if (self->_placeResponse != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_placeResponse, 7);
        }
    }
}

BOOL GEORPCorrectedSearchIsDirty(__unsafe_unretained GEORPCorrectedSearch *self)
{
    if (self == nil) {
        return NO;
    }
    
    BOOL dirty = NO
        || self->_flags.wrote_placeSearchRequest
        || (self->_flags.read_placeSearchRequest && GEOPlaceSearchRequestIsDirty(self->_placeSearchRequest))
        || self->_flags.wrote_placeSearchResponse
        || (self->_flags.read_placeSearchResponse && GEOPlaceSearchResponseIsDirty(self->_placeSearchResponse))
        || self->_flags.wrote_originalSearchResultIndex
        || self->_flags.wrote_correctedSearchResultIndex
        || self->_flags.wrote_preferredSearchDisplayLocation
        || self->_flags.read_preferredSearchDisplayLocation
        || self->_flags.wrote_placeRequest
        || (self->_flags.read_placeRequest && GEOPDPlaceRequestIsDirty(self->_placeRequest))
        || self->_flags.wrote_placeResponse
        || (self->_flags.read_placeResponse && GEOPDPlaceResponseIsDirty(self->_placeResponse))
    ;


    return dirty;
}


- (void)copyTo:(GEORPCorrectedSearch *)other
{
    [self readAll:NO];
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    other->_reader = _reader;
    other->_readerMarkPos = _readerMarkPos;
    other->_readerMarkLength = _readerMarkLength;
    os_unfair_lock_unlock(&_readerLock);
    if (_placeSearchRequest)
    {
        other.placeSearchRequest = _placeSearchRequest;
    }
    if (_placeSearchResponse)
    {
        other.placeSearchResponse = _placeSearchResponse;
    }
    if (self->_flags.has_originalSearchResultIndex)
    {
        other->_originalSearchResultIndex = _originalSearchResultIndex;
        other->_flags.has_originalSearchResultIndex = YES;
    }
    if (self->_flags.has_correctedSearchResultIndex)
    {
        other->_correctedSearchResultIndex = _correctedSearchResultIndex;
        other->_flags.has_correctedSearchResultIndex = YES;
    }
    if (_preferredSearchDisplayLocation)
    {
        other.preferredSearchDisplayLocation = _preferredSearchDisplayLocation;
    }
    if (_placeRequest)
    {
        other.placeRequest = _placeRequest;
    }
    if (_placeResponse)
    {
        other.placeResponse = _placeResponse;
    }
}

- (id)copyWithZone:(NSZone *)zone
{
    GEORPCorrectedSearch *copy = [[[self class] allocWithZone:zone] init];
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    @synchronized(reader) {
        if (reader) {
            BOOL wroteAny = NO
                || _flags.wrote_placeSearchRequest
                || _flags.wrote_placeSearchResponse
                || _flags.wrote_originalSearchResultIndex
                || _flags.wrote_correctedSearchResultIndex
                || _flags.wrote_preferredSearchDisplayLocation
                || _flags.wrote_placeRequest
                || _flags.wrote_placeResponse
            ;
            if (!wroteAny) {
                reader->_length = (NSUInteger)_readerMarkLength;
                [reader seekToOffset:(NSUInteger)_readerMarkPos];
                GEORPCorrectedSearchReadAllFrom(copy, reader, NO);
                return copy;
            }
            [self readAll:NO];
        }
    }
    copy->_placeSearchRequest = [_placeSearchRequest copyWithZone:zone];
    copy->_placeSearchResponse = [_placeSearchResponse copyWithZone:zone];
    if (self->_flags.has_originalSearchResultIndex)
    {
        copy->_originalSearchResultIndex = _originalSearchResultIndex;
        copy->_flags.has_originalSearchResultIndex = YES;
    }
    if (self->_flags.has_correctedSearchResultIndex)
    {
        copy->_correctedSearchResultIndex = _correctedSearchResultIndex;
        copy->_flags.has_correctedSearchResultIndex = YES;
    }
    copy->_preferredSearchDisplayLocation = [_preferredSearchDisplayLocation copyWithZone:zone];
    copy->_placeRequest = [_placeRequest copyWithZone:zone];
    copy->_placeResponse = [_placeResponse copyWithZone:zone];
    return copy;
}


- (BOOL)isEqual:(id)object
{
    GEORPCorrectedSearch *other = (GEORPCorrectedSearch *)object;
    if (![other isMemberOfClass:[self class]]) {
        return NO;
    }
    [self readAll:YES];
    [other readAll:YES];


    return YES
    &&
    ((!self->_placeSearchRequest && !other->_placeSearchRequest) || [self->_placeSearchRequest isEqual:other->_placeSearchRequest])
    &&
    ((!self->_placeSearchResponse && !other->_placeSearchResponse) || [self->_placeSearchResponse isEqual:other->_placeSearchResponse])
    &&
    ((self->_flags.has_originalSearchResultIndex && other->_flags.has_originalSearchResultIndex && self->_originalSearchResultIndex == other->_originalSearchResultIndex) || (!self->_flags.has_originalSearchResultIndex && !other->_flags.has_originalSearchResultIndex))
    &&
    ((self->_flags.has_correctedSearchResultIndex && other->_flags.has_correctedSearchResultIndex && self->_correctedSearchResultIndex == other->_correctedSearchResultIndex) || (!self->_flags.has_correctedSearchResultIndex && !other->_flags.has_correctedSearchResultIndex))
    &&
    ((!self->_preferredSearchDisplayLocation && !other->_preferredSearchDisplayLocation) || [self->_preferredSearchDisplayLocation isEqual:other->_preferredSearchDisplayLocation])
    &&
    ((!self->_placeRequest && !other->_placeRequest) || [self->_placeRequest isEqual:other->_placeRequest])
    &&
    ((!self->_placeResponse && !other->_placeResponse) || [self->_placeResponse isEqual:other->_placeResponse])
    ;
}

- (NSUInteger)hash
{
    [self readAll:YES];
    NSUInteger value = 0;

    return value
    ^
    [self->_placeSearchRequest hash]
    ^
    [self->_placeSearchResponse hash]
    ^
    (self->_flags.has_originalSearchResultIndex ? PBHashInt((NSUInteger)self->_originalSearchResultIndex) : 0)
    ^
    (self->_flags.has_correctedSearchResultIndex ? PBHashInt((NSUInteger)self->_correctedSearchResultIndex) : 0)
    ^
    [self->_preferredSearchDisplayLocation hash]
    ^
    [self->_placeRequest hash]
    ^
    [self->_placeResponse hash]
    ;
}

- (void)mergeFrom:(GEORPCorrectedSearch *)other
{
    [other readAll:NO];
    if (self->_placeSearchRequest && other->_placeSearchRequest)
    {
        [self->_placeSearchRequest mergeFrom:other->_placeSearchRequest];
    }
    else if (!self->_placeSearchRequest && other->_placeSearchRequest)
    {
        [self setPlaceSearchRequest:other->_placeSearchRequest];
    }
    if (self->_placeSearchResponse && other->_placeSearchResponse)
    {
        [self->_placeSearchResponse mergeFrom:other->_placeSearchResponse];
    }
    else if (!self->_placeSearchResponse && other->_placeSearchResponse)
    {
        [self setPlaceSearchResponse:other->_placeSearchResponse];
    }
    if (other->_flags.has_originalSearchResultIndex)
    {
        self->_originalSearchResultIndex = other->_originalSearchResultIndex;
        self->_flags.has_originalSearchResultIndex = 1;
    }
    if (other->_flags.has_correctedSearchResultIndex)
    {
        self->_correctedSearchResultIndex = other->_correctedSearchResultIndex;
        self->_flags.has_correctedSearchResultIndex = 1;
    }
    if (other->_preferredSearchDisplayLocation)
    {
        [self setPreferredSearchDisplayLocation:other->_preferredSearchDisplayLocation];
    }
    if (self->_placeRequest && other->_placeRequest)
    {
        [self->_placeRequest mergeFrom:other->_placeRequest];
    }
    else if (!self->_placeRequest && other->_placeRequest)
    {
        [self setPlaceRequest:other->_placeRequest];
    }
    if (self->_placeResponse && other->_placeResponse)
    {
        [self->_placeResponse mergeFrom:other->_placeResponse];
    }
    else if (!self->_placeResponse && other->_placeResponse)
    {
        [self setPlaceResponse:other->_placeResponse];
    }
}


@end


