// This file was automatically generated by gyb
// DO NOT EDIT!
// Compiled from community_feedback.proto

#import "GEORPFeedbackResponse.h"
#import <ProtocolBuffer/PBConstants.h>
#import <ProtocolBuffer/PBHashUtil.h>
#import <ProtocolBuffer/PBDataReader.h>

#import <GeoServices/GEORPFeedbackResult.h>

#if !__has_feature(objc_arc)
# error This generated file depends on ARC but it is not enabled
#endif

@implementation GEORPFeedbackResponse


- (GEOStatusCode)status
{
    return _flags.has_status ? _status : GEOStatusCode_STATUS_SUCCESS;
}
- (void)setStatus:(GEOStatusCode)v
{
    _flags.has_status = 1;
    _status = v;
}
- (void)setHasStatus:(BOOL)f
{
    _flags.has_status = f ? 1 : 0;
}
- (BOOL)hasStatus
{
    return (BOOL)_flags.has_status;
}
- (NSString *)statusAsString:(GEOStatusCode)value
{
    return GEOStatusCodeAsString(value);
}
- (GEOStatusCode)StringAsStatus:(NSString *)str
{
    return StringAsGEOStatusCode(str);
}

- (GEORPFeedbackRequestType)feedbackRequestType
{
    return _flags.has_feedbackRequestType ? _feedbackRequestType : GEORPFeedbackRequestType_FEEDBACK_REQUEST_TYPE_UNKNOWN;
}
- (void)setFeedbackRequestType:(GEORPFeedbackRequestType)v
{
    _flags.has_feedbackRequestType = 1;
    _feedbackRequestType = v;
}
- (void)setHasFeedbackRequestType:(BOOL)f
{
    _flags.has_feedbackRequestType = f ? 1 : 0;
}
- (BOOL)hasFeedbackRequestType
{
    return (BOOL)_flags.has_feedbackRequestType;
}
- (NSString *)feedbackRequestTypeAsString:(GEORPFeedbackRequestType)value
{
    return GEORPFeedbackRequestTypeAsString(value);
}
- (GEORPFeedbackRequestType)StringAsFeedbackRequestType:(NSString *)str
{
    return StringAsGEORPFeedbackRequestType(str);
}

- (BOOL)hasFeedbackResult
{
    return _feedbackResult != nil;
}
- (GEORPFeedbackResult *)feedbackResult
{
    return _feedbackResult;
}
- (void)setFeedbackResult:(GEORPFeedbackResult *)v
{
    _feedbackResult = v;
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"%@ %@", [super description], [self dictionaryRepresentation]];
}

- (NSDictionary *)dictionaryRepresentation
{
    [self readAll:YES];
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    if (self->_flags.has_status)
    {
        [dict setObject:GEOStatusCodeAsString(self->_status) forKey:@"status"];
    }

    if (self->_flags.has_feedbackRequestType)
    {
        [dict setObject:GEORPFeedbackRequestTypeAsString(self->_feedbackRequestType) forKey:@"feedback_request_type"];
    }

    {
        GEORPFeedbackResult * value = self.feedbackResult;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"feedback_result"];
        }
    }


    if (_unknownFields)
        [dict setObject:[_unknownFields dictionaryRepresentation] forKey:@"Unknown Fields"];

    return dict;
}


#define TAG_PARSE_ALL_RECURSIVE     (UINT32_MAX)
#define TAG_PARSE_ALL_NON_RECURSIVE (UINT32_MAX-1)
#define TAG_PARSE_INITIAL           (UINT32_MAX-2)
#define TAG_UNKNOWN_FIELDS          (UINT32_MAX-3)

- (void)readAll:(BOOL)recursively { /* noop */ }
BOOL GEORPFeedbackResponseReadAllFrom(__unsafe_unretained GEORPFeedbackResponse *self, __unsafe_unretained PBDataReader *reader, BOOL recursively) {
    static const uint32_t recursiveTag[] = {TAG_PARSE_ALL_RECURSIVE, 0};

    @synchronized(reader) {
        BOOL result = GEORPFeedbackResponseReadSpecified(self, reader, recursively ? recursiveTag : nil);
        return result;
    }
}
BOOL GEORPFeedbackResponseReadFrom(__unsafe_unretained GEORPFeedbackResponse *self, __unsafe_unretained PBDataReader *reader) {
    @synchronized(reader) {
        return GEORPFeedbackResponseReadAllFrom(self, reader, NO);
    }
}

BOOL GEORPFeedbackResponseReadSpecified(__unsafe_unretained GEORPFeedbackResponse *self, __unsafe_unretained PBDataReader *reader, const uint32_t *tags) {
    if (reader == nil) {
        return NO;
    }
    #define shouldParseUnknown YES
    __attribute__((unused)) BOOL const recursively = (tags != nil && tags[0] == TAG_PARSE_ALL_RECURSIVE);
    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }
        
    #define shouldParseTag YES

        switch (tag) {

            case 1 /* status */:
            {
                self->_flags.has_status = YES;
                self->_status = PBReaderReadInt32(reader);

            }
            break;
            case 2 /* feedbackRequestType */:
            {
                self->_flags.has_feedbackRequestType = YES;
                self->_feedbackRequestType = PBReaderReadInt32(reader);

            }
            break;
            case 3 /* feedbackResult */:
            {
                GEORPFeedbackResult *new_feedbackResult = [[GEORPFeedbackResult alloc] init];
                self->_feedbackResult = new_feedbackResult;
                PBDataReaderMark mark_feedbackResult;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_feedbackResult);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEORPFeedbackResultReadAllFrom(new_feedbackResult, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_feedbackResult);

            }
            break;
            default:
                if (!self->_unknownFields)
                    self->_unknownFields = [[PBUnknownFields alloc] init];
                if (!PBUnknownFieldAdd(self->_unknownFields, tag, aType, reader))
                    return NO;
                break;
        }
    }



    #undef shouldParseTag
    #undef shouldParseUnknown
    #undef recursively
    return !PBReaderHasError(reader);
}

+ (BOOL)isValid:(__unsafe_unretained PBDataReader *)reader
{
    return GEORPFeedbackResponseIsValid(reader);
}

BOOL GEORPFeedbackResponseIsValid(__unsafe_unretained PBDataReader *reader) {
    PBDataReaderMark resetMark;
    resetMark.pos = reader.position;
    resetMark.length = reader.length;
    #define returnValue(X) do { \
        const BOOL v = X; \
        PBReaderRecallMark(reader, &resetMark); \
        return v; \
    } while(0)
    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }

        switch (tag) {

            case 1 /* status */:
                if (TYPE_VARINT != aType)
                    returnValue(NO);
                PBReaderReadInt32(reader);
                break;
            case 2 /* feedbackRequestType */:
                if (TYPE_VARINT != aType)
                    returnValue(NO);
                PBReaderReadInt32(reader);
                break;
            case 3 /* feedbackResult */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_feedbackResult;
                    if (!PBReaderPlaceMark(reader, &mark_feedbackResult))
                        returnValue(NO);
                    if (!GEORPFeedbackResultIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_feedbackResult);
                }
                break;
            default:
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    returnValue(NO);
                break;
        }
    }
    returnValue(!PBReaderHasError(reader));
    #undef returnValue
}

- (BOOL)readFrom:(PBDataReader *)reader
{
    return GEORPFeedbackResponseReadAllFrom(self, reader, NO);
}

- (void)writeTo:(PBDataWriter *)writer
{

    /* status */
    {
        if (self->_flags.has_status)
        {
            PBDataWriterWriteInt32Field(writer, self->_status, 1);
        }
    }

    /* feedbackRequestType */
    {
        if (self->_flags.has_feedbackRequestType)
        {
            PBDataWriterWriteInt32Field(writer, self->_feedbackRequestType, 2);
        }
    }

    /* feedbackResult */
    {
        if (self->_feedbackResult != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_feedbackResult, 3);
        }
    }
    /* Unknown Fields */
    {
        [_unknownFields writeTo:writer];
    }
}



- (void)copyTo:(GEORPFeedbackResponse *)other
{
    [self readAll:NO];
    if (self->_flags.has_status)
    {
        other->_status = _status;
        other->_flags.has_status = YES;
    }
    if (self->_flags.has_feedbackRequestType)
    {
        other->_feedbackRequestType = _feedbackRequestType;
        other->_flags.has_feedbackRequestType = YES;
    }
    if (_feedbackResult)
    {
        other.feedbackResult = _feedbackResult;
    }
}

- (id)copyWithZone:(NSZone *)zone
{
    GEORPFeedbackResponse *copy = [[[self class] allocWithZone:zone] init];
    if (self->_flags.has_status)
    {
        copy->_status = _status;
        copy->_flags.has_status = YES;
    }
    if (self->_flags.has_feedbackRequestType)
    {
        copy->_feedbackRequestType = _feedbackRequestType;
        copy->_flags.has_feedbackRequestType = YES;
    }
    copy->_feedbackResult = [_feedbackResult copyWithZone:zone];
    copy->_unknownFields = _unknownFields;
    return copy;
}


- (BOOL)isEqual:(id)object
{
    GEORPFeedbackResponse *other = (GEORPFeedbackResponse *)object;
    if (![other isMemberOfClass:[self class]]) {
        return NO;
    }
    [self readAll:YES];
    [other readAll:YES];


    return YES
    &&
    ((self->_flags.has_status && other->_flags.has_status && self->_status == other->_status) || (!self->_flags.has_status && !other->_flags.has_status))
    &&
    ((self->_flags.has_feedbackRequestType && other->_flags.has_feedbackRequestType && self->_feedbackRequestType == other->_feedbackRequestType) || (!self->_flags.has_feedbackRequestType && !other->_flags.has_feedbackRequestType))
    &&
    ((!self->_feedbackResult && !other->_feedbackResult) || [self->_feedbackResult isEqual:other->_feedbackResult])
    ;
}

- (NSUInteger)hash
{
    [self readAll:YES];
    NSUInteger value = 0;

    return value
    ^
    (self->_flags.has_status ? PBHashInt((NSUInteger)self->_status) : 0)
    ^
    (self->_flags.has_feedbackRequestType ? PBHashInt((NSUInteger)self->_feedbackRequestType) : 0)
    ^
    [self->_feedbackResult hash]
    ;
}

- (void)mergeFrom:(GEORPFeedbackResponse *)other
{
    [other readAll:NO];
    if (other->_flags.has_status)
    {
        self->_status = other->_status;
        self->_flags.has_status = 1;
    }
    if (other->_flags.has_feedbackRequestType)
    {
        self->_feedbackRequestType = other->_feedbackRequestType;
        self->_flags.has_feedbackRequestType = 1;
    }
    if (self->_feedbackResult && other->_feedbackResult)
    {
        [self->_feedbackResult mergeFrom:other->_feedbackResult];
    }
    else if (!self->_feedbackResult && other->_feedbackResult)
    {
        [self setFeedbackResult:other->_feedbackResult];
    }
}

- (PBUnknownFields *)unknownFields
{
    return _unknownFields;
}
- (void)clearUnknownFields:(BOOL)recursively
{
    _unknownFields = nil;
    if (!recursively) {
        return;
    }
    [self readAll:NO];
    [_feedbackResult clearUnknownFields:YES];
}

@end


