// This file was automatically generated by gyb
// DO NOT EDIT!
// Compiled from community_feedback.proto

#import "GEORPTileFeedback.h"
#import <ProtocolBuffer/PBConstants.h>
#import <ProtocolBuffer/PBHashUtil.h>
#import <ProtocolBuffer/PBDataReader.h>
#import <os/lock_private.h>

#import <GeoServices/GEORPCorrectedCoordinate.h>
#import <GeoServices/GEORPCorrectedLabel.h>

#if !__has_feature(objc_arc)
# error This generated file depends on ARC but it is not enabled
#endif

@implementation GEORPTileFeedback

- (instancetype)init
{
    self = [super init];
    if (self == nil) {
        return nil;
    }

    _readerLock = OS_UNFAIR_LOCK_INIT;
    return self;
}

- (instancetype)initWithData:(NSData *)data
{
    self = [super initWithData:data];
    if (self == nil) {
        return nil;
    }

    _readerLock = OS_UNFAIR_LOCK_INIT;
    return self;
}

- (void)_readLabel {
    if (_flags.read_label) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_label) {
            static const uint32_t tags[] = {1, 0};
            GEORPTileFeedbackReadSpecified(self, reader, tags);
        }
    }
}
- (BOOL)hasLabel
{
    [self _readLabel];
    return _label != nil;
}
- (GEORPCorrectedLabel *)label
{
    [self _readLabel];
    return _label;
}
- (void)setLabel:(GEORPCorrectedLabel *)v
{
    _flags.read_label = 1;
    _flags.wrote_label = 1;
    _label = v;
}

- (void)_readCoordinate {
    if (_flags.read_coordinate) return;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return;
    @synchronized(reader) {
        if (!_flags.read_coordinate) {
            static const uint32_t tags[] = {2, 0};
            GEORPTileFeedbackReadSpecified(self, reader, tags);
        }
    }
}
- (BOOL)hasCoordinate
{
    [self _readCoordinate];
    return _coordinate != nil;
}
- (GEORPCorrectedCoordinate *)coordinate
{
    [self _readCoordinate];
    return _coordinate;
}
- (void)setCoordinate:(GEORPCorrectedCoordinate *)v
{
    _flags.read_coordinate = 1;
    _flags.wrote_coordinate = 1;
    _coordinate = v;
}

- (GEORPTileFeedback_TileCorrectionType)type
{
    return _flags.has_type ? _type : GEORPTileFeedback_TileCorrectionType_TILE_CORRECTION_TYPE_UNKNOWN;
}
- (void)setType:(GEORPTileFeedback_TileCorrectionType)v
{
    _flags.wrote_type = 1;
    _flags.has_type = 1;
    _type = v;
}
- (void)setHasType:(BOOL)f
{
    _flags.wrote_type = 1;
    _flags.has_type = f ? 1 : 0;
}
- (BOOL)hasType
{
    return (BOOL)_flags.has_type;
}
- (NSString *)typeAsString:(GEORPTileFeedback_TileCorrectionType)value
{
    return GEORPTileFeedback_TileCorrectionTypeAsString(value);
}
- (GEORPTileFeedback_TileCorrectionType)StringAsType:(NSString *)str
{
    return StringAsGEORPTileFeedback_TileCorrectionType(str);
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"%@ %@", [super description], [self dictionaryRepresentation]];
}

- (NSDictionary *)dictionaryRepresentation
{
    [self readAll:YES];
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    {
        GEORPCorrectedLabel * value = self.label;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"label"];
        }
    }

    {
        GEORPCorrectedCoordinate * value = self.coordinate;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"coordinate"];
        }
    }

    if (self->_flags.has_type)
    {
        [dict setObject:GEORPTileFeedback_TileCorrectionTypeAsString(self->_type) forKey:@"type"];
    }


    if (_unknownFields)
        [dict setObject:[_unknownFields dictionaryRepresentation] forKey:@"Unknown Fields"];

    return dict;
}


#define TAG_PARSE_ALL_RECURSIVE     (UINT32_MAX)
#define TAG_PARSE_ALL_NON_RECURSIVE (UINT32_MAX-1)
#define TAG_PARSE_INITIAL           (UINT32_MAX-2)
#define TAG_UNKNOWN_FIELDS          (UINT32_MAX-3)

- (void)readAll:(BOOL)recursively {
    os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (reader == nil) return;
    @synchronized(reader) {
        static const uint32_t recursiveTag[] = {TAG_PARSE_ALL_RECURSIVE, 0};
        static const uint32_t nonRecursiveTag[] = {TAG_PARSE_ALL_NON_RECURSIVE, 0};
        GEORPTileFeedbackReadSpecified(self, reader, recursively ? recursiveTag : nonRecursiveTag);
    }
}
BOOL GEORPTileFeedbackReadAllFrom(__unsafe_unretained GEORPTileFeedback *self, __unsafe_unretained PBDataReader *reader, BOOL recursively) {
    if (self->_readerMarkLength != 0) {
        [NSException raise:NSInvalidArgumentException format:@"GEORPTileFeedbackReadAllFrom can only be called once per object"];
        return NO;
    }

    if (reader.position > UINT32_MAX || reader.length > UINT32_MAX) {
        os_log_fault(OS_LOG_DEFAULT, "Cannot decode data with position/length > UINT32_MAX");
        return NO;
    }

    static const uint32_t recursiveTag[] = {TAG_PARSE_INITIAL, TAG_PARSE_ALL_RECURSIVE, 0};
    static const uint32_t initialTag[] = {TAG_PARSE_INITIAL, 0};

    @synchronized(reader) {
        os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
        self->_reader = reader;
        os_unfair_lock_unlock(&(self->_readerLock));

        self->_readerMarkPos = (uint32_t)reader.position;
        self->_readerMarkLength = (uint32_t)reader.length;
        BOOL result = GEORPTileFeedbackReadSpecified(self, reader, recursively ? recursiveTag : initialTag);
        return result;
    }
}

BOOL GEORPTileFeedbackReadFrom(__unsafe_unretained GEORPTileFeedback *self, __unsafe_unretained PBDataReader *reader) {
    @synchronized(reader) {
        return GEORPTileFeedbackReadAllFrom(self, reader, NO);
    }
}

BOOL GEORPTileFeedbackReadSpecified(__unsafe_unretained GEORPTileFeedback *self, __unsafe_unretained PBDataReader *reader, const uint32_t *tags) {
    if (reader == nil) {
        return NO;
    }
    reader->_length = (NSUInteger)self->_readerMarkLength;
    [reader seekToOffset:(NSUInteger)self->_readerMarkPos];
    uint32_t readLazyCount = 0
        + self->_flags.read_label
        + self->_flags.read_coordinate
        + self->_flags.read_unknownFields
        ;
    #define requiredLazyFieldCount 1 // objc_msg_parse_all_threshold = 0.8

    BOOL readAll = NO;
    __attribute__((unused)) BOOL recursively = NO;
    BOOL shouldParseUnknown = NO;
    BOOL isInitial = NO;
    size_t tagsRemaining = 0;
    for (; tags[tagsRemaining] != 0; ++tagsRemaining) {
        switch (tags[tagsRemaining]) {
            case TAG_PARSE_ALL_RECURSIVE:
                recursively = YES;
                readAll = YES;
                shouldParseUnknown = YES;
                break;
            case TAG_PARSE_ALL_NON_RECURSIVE:
                readAll = YES;
                shouldParseUnknown = YES;
                break;
            case TAG_PARSE_INITIAL:
                isInitial = YES;
                break;
            case TAG_UNKNOWN_FIELDS:
                shouldParseUnknown = YES;
                ++readLazyCount;
                break;
            default:
                ++readLazyCount;
                break;
            }
    }
    if (!readAll && readLazyCount >= requiredLazyFieldCount) {
        readAll = YES;
        shouldParseUnknown = YES;
    }
    const BOOL stopWhenNoMoreTagsRemaining = !(readAll || shouldParseUnknown);
    if (readAll || isInitial) tags = NULL;

    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }
        
        BOOL shouldParseTag = readAll;
        for (size_t i = 0; tags != NULL && !shouldParseTag && tags[i] != 0; ++i) {
            shouldParseTag = (tags[i] == tag);
        }

        switch (tag) {

            case 1 /* label */:
            {
                if (!shouldParseTag || self->_flags.read_label) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    if (shouldParseTag && self->_flags.read_label) {
                        --tagsRemaining;
                    }
                    break;
                }
                GEORPCorrectedLabel *new_label = [[GEORPCorrectedLabel alloc] init];
                self->_label = new_label;
                PBDataReaderMark mark_label;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_label);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEORPCorrectedLabelReadAllFrom(new_label, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_label);

                --tagsRemaining;
            }
            break;
            case 2 /* coordinate */:
            {
                if (!shouldParseTag || self->_flags.read_coordinate) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    if (shouldParseTag && self->_flags.read_coordinate) {
                        --tagsRemaining;
                    }
                    break;
                }
                GEORPCorrectedCoordinate *new_coordinate = [[GEORPCorrectedCoordinate alloc] init];
                self->_coordinate = new_coordinate;
                PBDataReaderMark mark_coordinate;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_coordinate);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEORPCorrectedCoordinateReadAllFrom(new_coordinate, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_coordinate);

                --tagsRemaining;
            }
            break;
            case 3 /* type */:
            {
                if (!isInitial) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    break;
                }
                self->_flags.has_type = YES;
                self->_type = PBReaderReadInt32(reader);

            }
            break;
            default:
                if (!shouldParseUnknown || self->_flags.read_unknownFields) {
                    if (!PBReaderSkipValueWithTag(reader, tag, aType))
                        return NO;
                    break;
                }
                if (!self->_unknownFields)
                    self->_unknownFields = [[PBUnknownFields alloc] init];
                if (!PBUnknownFieldAdd(self->_unknownFields, tag, aType, reader))
                    return NO;
                break;
        }
        if (stopWhenNoMoreTagsRemaining && tagsRemaining == 0) {
            break;
        }
    }

    if (shouldParseUnknown) {
        self->_flags.read_unknownFields = YES;
    }

    if (readAll) {
        if (recursively) {
            [self->_label readAll:YES];
            [self->_coordinate readAll:YES];
        }
        self->_flags.read_label = YES;
        self->_flags.read_coordinate = YES;
    } else {
        for (size_t i = 0; tags != NULL && tags[i] != 0; ++i) {
            switch (tags[i]) {
                case 1 /* label */:
                    self->_flags.read_label = YES;
                    break;
                case 2 /* coordinate */:
                    self->_flags.read_coordinate = YES;
                    break;
            }
        }
    }

    #undef requiredLazyFieldCount
    if (readAll) {
        // reader is __unsafe_unretained
        const BOOL hadError = PBReaderHasError(reader);
        os_unfair_lock_lock_with_options(&(self->_readerLock), OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
        self->_reader = nil;
        os_unfair_lock_unlock(&(self->_readerLock));
        return !hadError;
    }
    return !PBReaderHasError(reader);
}

+ (BOOL)isValid:(__unsafe_unretained PBDataReader *)reader
{
    return GEORPTileFeedbackIsValid(reader);
}

BOOL GEORPTileFeedbackIsValid(__unsafe_unretained PBDataReader *reader) {
    PBDataReaderMark resetMark;
    resetMark.pos = reader.position;
    resetMark.length = reader.length;
    #define returnValue(X) do { \
        const BOOL v = X; \
        PBReaderRecallMark(reader, &resetMark); \
        return v; \
    } while(0)
    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }

        switch (tag) {

            case 1 /* label */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_label;
                    if (!PBReaderPlaceMark(reader, &mark_label))
                        returnValue(NO);
                    if (!GEORPCorrectedLabelIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_label);
                }
                break;
            case 2 /* coordinate */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_coordinate;
                    if (!PBReaderPlaceMark(reader, &mark_coordinate))
                        returnValue(NO);
                    if (!GEORPCorrectedCoordinateIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_coordinate);
                }
                break;
            case 3 /* type */:
                if (TYPE_VARINT != aType)
                    returnValue(NO);
                PBReaderReadInt32(reader);
                break;
            default:
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    returnValue(NO);
                break;
        }
    }
    returnValue(!PBReaderHasError(reader));
    #undef returnValue
}

- (BOOL)readFrom:(PBDataReader *)reader
{
    return GEORPTileFeedbackReadAllFrom(self, reader, NO);
}

- (void)writeTo:(PBDataWriter *)writer
{
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    @synchronized(reader) {
        if (reader) {
            if (!GEORPTileFeedbackIsDirty(self)) {
                reader->_length = (NSUInteger)_readerMarkLength;
                [reader seekToOffset:(NSUInteger)_readerMarkPos];
                uint32_t length = (_readerMarkLength - _readerMarkPos);
                NSData *data = [reader readBytes:length];
                [writer writeData:data];
                return;
            }
        }
    }

    [self readAll:NO];

    /* label */
    {
        if (self->_label != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_label, 1);
        }
    }

    /* coordinate */
    {
        if (self->_coordinate != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_coordinate, 2);
        }
    }

    /* type */
    {
        if (self->_flags.has_type)
        {
            PBDataWriterWriteInt32Field(writer, self->_type, 3);
        }
    }
    /* Unknown Fields */
    {
        [_unknownFields writeTo:writer];
    }
}

BOOL GEORPTileFeedbackIsDirty(__unsafe_unretained GEORPTileFeedback *self)
{
    if (self == nil) {
        return NO;
    }
    
    BOOL dirty = NO
        || self->_flags.wrote_label
        || (self->_flags.read_label && GEORPCorrectedLabelIsDirty(self->_label))
        || self->_flags.wrote_coordinate
        || (self->_flags.read_coordinate && GEORPCorrectedCoordinateIsDirty(self->_coordinate))
        || self->_flags.wrote_type
        || self->_flags.wrote_unknownFields
    ;


    return dirty;
}


- (void)copyTo:(GEORPTileFeedback *)other
{
    [self readAll:NO];
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    other->_reader = _reader;
    other->_readerMarkPos = _readerMarkPos;
    other->_readerMarkLength = _readerMarkLength;
    os_unfair_lock_unlock(&_readerLock);
    if (_label)
    {
        other.label = _label;
    }
    if (_coordinate)
    {
        other.coordinate = _coordinate;
    }
    if (self->_flags.has_type)
    {
        other->_type = _type;
        other->_flags.has_type = YES;
    }
}

- (id)copyWithZone:(NSZone *)zone
{
    GEORPTileFeedback *copy = [[[self class] allocWithZone:zone] init];
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    @synchronized(reader) {
        if (reader) {
            BOOL wroteAny = NO
                || _flags.wrote_label
                || _flags.wrote_coordinate
                || _flags.wrote_type
                || _flags.wrote_unknownFields
            ;
            if (!wroteAny) {
                reader->_length = (NSUInteger)_readerMarkLength;
                [reader seekToOffset:(NSUInteger)_readerMarkPos];
                GEORPTileFeedbackReadAllFrom(copy, reader, NO);
                return copy;
            }
            [self readAll:NO];
        }
    }
    copy->_label = [_label copyWithZone:zone];
    copy->_coordinate = [_coordinate copyWithZone:zone];
    if (self->_flags.has_type)
    {
        copy->_type = _type;
        copy->_flags.has_type = YES;
    }
    copy->_unknownFields = _unknownFields;
    return copy;
}


- (BOOL)isEqual:(id)object
{
    GEORPTileFeedback *other = (GEORPTileFeedback *)object;
    if (![other isMemberOfClass:[self class]]) {
        return NO;
    }
    [self readAll:YES];
    [other readAll:YES];


    return YES
    &&
    ((!self->_label && !other->_label) || [self->_label isEqual:other->_label])
    &&
    ((!self->_coordinate && !other->_coordinate) || [self->_coordinate isEqual:other->_coordinate])
    &&
    ((self->_flags.has_type && other->_flags.has_type && self->_type == other->_type) || (!self->_flags.has_type && !other->_flags.has_type))
    ;
}

- (NSUInteger)hash
{
    [self readAll:YES];
    NSUInteger value = 0;

    return value
    ^
    [self->_label hash]
    ^
    [self->_coordinate hash]
    ^
    (self->_flags.has_type ? PBHashInt((NSUInteger)self->_type) : 0)
    ;
}

- (void)mergeFrom:(GEORPTileFeedback *)other
{
    [other readAll:NO];
    if (self->_label && other->_label)
    {
        [self->_label mergeFrom:other->_label];
    }
    else if (!self->_label && other->_label)
    {
        [self setLabel:other->_label];
    }
    if (self->_coordinate && other->_coordinate)
    {
        [self->_coordinate mergeFrom:other->_coordinate];
    }
    else if (!self->_coordinate && other->_coordinate)
    {
        [self setCoordinate:other->_coordinate];
    }
    if (other->_flags.has_type)
    {
        self->_type = other->_type;
        self->_flags.has_type = 1;
    }
}

- (PBUnknownFields *)unknownFields
{
    if (_flags.read_unknownFields) return _unknownFields;
    os_unfair_lock_lock_with_options(&_readerLock, OS_UNFAIR_LOCK_DATA_SYNCHRONIZATION);
    PBDataReader *reader = _reader;
    os_unfair_lock_unlock(&_readerLock);
    if (!reader) return _unknownFields;
    @synchronized(reader) {
        if (!_flags.read_unknownFields) {
            static const uint32_t tags[] = {TAG_UNKNOWN_FIELDS, 0};
            GEORPTileFeedbackReadSpecified(self, reader, tags);
        }
    }
    return _unknownFields;
}
- (void)clearUnknownFields:(BOOL)recursively
{
    _flags.read_unknownFields = 1;
    _flags.wrote_unknownFields = 1;
    _unknownFields = nil;
    if (!recursively) {
        return;
    }
    [self readAll:NO];
}

@end


