// This file was automatically generated by gyb
// DO NOT EDIT!
// Compiled from reportaproblem.proto

#import "GEORPCarPlayAuxiliaryControl.h"
#import <ProtocolBuffer/PBConstants.h>
#import <ProtocolBuffer/PBHashUtil.h>
#import <ProtocolBuffer/PBDataReader.h>

#import <GeoServices/GEOCarInfo.h>

#if !__has_feature(objc_arc)
# error This generated file depends on ARC but it is not enabled
#endif

@implementation GEORPCarPlayAuxiliaryControl


- (BOOL)hasCarInfo
{
    return _carInfo != nil;
}
- (GEOCarInfo *)carInfo
{
    return _carInfo;
}
- (void)setCarInfo:(GEOCarInfo *)v
{
    _carInfo = v;
}


- (NSString *)description
{
    return [NSString stringWithFormat:@"%@ %@", [super description], [self dictionaryRepresentation]];
}

- (NSDictionary *)dictionaryRepresentation
{
    [self readAll:YES];
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    {
        GEOCarInfo * value = self.carInfo;
        if (value) {
            [dict setObject:[value dictionaryRepresentation] forKey:@"car_info"];
        }
    }



    return dict;
}


#define TAG_PARSE_ALL_RECURSIVE     (UINT32_MAX)
#define TAG_PARSE_ALL_NON_RECURSIVE (UINT32_MAX-1)
#define TAG_PARSE_INITIAL           (UINT32_MAX-2)
#define TAG_UNKNOWN_FIELDS          (UINT32_MAX-3)

- (void)readAll:(BOOL)recursively { /* noop */ }
BOOL GEORPCarPlayAuxiliaryControlReadAllFrom(__unsafe_unretained GEORPCarPlayAuxiliaryControl *self, __unsafe_unretained PBDataReader *reader, BOOL recursively) {
    static const uint32_t recursiveTag[] = {TAG_PARSE_ALL_RECURSIVE, 0};

    @synchronized(reader) {
        BOOL result = GEORPCarPlayAuxiliaryControlReadSpecified(self, reader, recursively ? recursiveTag : nil);
        return result;
    }
}
BOOL GEORPCarPlayAuxiliaryControlReadFrom(__unsafe_unretained GEORPCarPlayAuxiliaryControl *self, __unsafe_unretained PBDataReader *reader) {
    @synchronized(reader) {
        return GEORPCarPlayAuxiliaryControlReadAllFrom(self, reader, NO);
    }
}

BOOL GEORPCarPlayAuxiliaryControlReadSpecified(__unsafe_unretained GEORPCarPlayAuxiliaryControl *self, __unsafe_unretained PBDataReader *reader, const uint32_t *tags) {
    if (reader == nil) {
        return NO;
    }
    #define shouldParseUnknown YES
    __attribute__((unused)) BOOL const recursively = (tags != nil && tags[0] == TAG_PARSE_ALL_RECURSIVE);
    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }
        
    #define shouldParseTag YES

        switch (tag) {

            case 1 /* carInfo */:
            {
                GEOCarInfo *new_carInfo = [[GEOCarInfo alloc] init];
                self->_carInfo = new_carInfo;
                PBDataReaderMark mark_carInfo;
                BOOL markError = !PBReaderPlaceMark(reader, &mark_carInfo);
                if (markError)
                {
                    return NO;
                }
                BOOL inError = !GEOCarInfoReadAllFrom(new_carInfo, reader, recursively);
                if (inError)
                {
                    return NO;
                }
                PBReaderRecallMark(reader, &mark_carInfo);

            }
            break;
            default:
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    return NO;
                break;
        }
    }



    #undef shouldParseTag
    #undef shouldParseUnknown
    #undef recursively
    return !PBReaderHasError(reader);
}

+ (BOOL)isValid:(__unsafe_unretained PBDataReader *)reader
{
    return GEORPCarPlayAuxiliaryControlIsValid(reader);
}

BOOL GEORPCarPlayAuxiliaryControlIsValid(__unsafe_unretained PBDataReader *reader) {
    PBDataReaderMark resetMark;
    resetMark.pos = reader.position;
    resetMark.length = reader.length;
    #define returnValue(X) do { \
        const BOOL v = X; \
        PBReaderRecallMark(reader, &resetMark); \
        return v; \
    } while(0)
    while (PBReaderHasMoreData(reader)) {
        uint32_t tag = 0;
        uint8_t aType = 0;
        PBReaderReadTag32AndType(reader, &tag, &aType);

        if (PBReaderHasError(reader))
            break;

        if (aType == TYPE_END_GROUP) {
            break;
        }

        switch (tag) {

            case 1 /* carInfo */:
                if (TYPE_LENGTH_DELIMITED != aType)
                    returnValue(NO);
                {
                    PBDataReaderMark mark_carInfo;
                    if (!PBReaderPlaceMark(reader, &mark_carInfo))
                        returnValue(NO);
                    if (!GEOCarInfoIsValid(reader))
                        returnValue(NO);
                    PBReaderRecallMark(reader, &mark_carInfo);
                }
                break;
            default:
                if (!PBReaderSkipValueWithTag(reader, tag, aType))
                    returnValue(NO);
                break;
        }
    }
    returnValue(!PBReaderHasError(reader));
    #undef returnValue
}

- (BOOL)readFrom:(PBDataReader *)reader
{
    return GEORPCarPlayAuxiliaryControlReadAllFrom(self, reader, NO);
}

- (void)writeTo:(PBDataWriter *)writer
{

    /* carInfo */
    {
        if (self->_carInfo != nil)
        {
            PBDataWriterWriteSubmessage(writer, self->_carInfo, 1);
        }
    }
}



- (void)copyTo:(GEORPCarPlayAuxiliaryControl *)other
{
    [self readAll:NO];
    if (_carInfo)
    {
        other.carInfo = _carInfo;
    }
}

- (id)copyWithZone:(NSZone *)zone
{
    GEORPCarPlayAuxiliaryControl *copy = [[[self class] allocWithZone:zone] init];
    copy->_carInfo = [_carInfo copyWithZone:zone];
    return copy;
}


- (BOOL)isEqual:(id)object
{
    GEORPCarPlayAuxiliaryControl *other = (GEORPCarPlayAuxiliaryControl *)object;
    if (![other isMemberOfClass:[self class]]) {
        return NO;
    }
    [self readAll:YES];
    [other readAll:YES];


    return YES
    &&
    ((!self->_carInfo && !other->_carInfo) || [self->_carInfo isEqual:other->_carInfo])
    ;
}

- (NSUInteger)hash
{
    [self readAll:YES];
    NSUInteger value = 0;

    return value
    ^
    [self->_carInfo hash]
    ;
}

- (void)mergeFrom:(GEORPCarPlayAuxiliaryControl *)other
{
    [other readAll:NO];
    if (self->_carInfo && other->_carInfo)
    {
        [self->_carInfo mergeFrom:other->_carInfo];
    }
    else if (!self->_carInfo && other->_carInfo)
    {
        [self setCarInfo:other->_carInfo];
    }
}


@end


